services:
  postgres:
    image: postgres:15
    container_name: postgres_db_donare
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: donareDB
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    networks:
      - postgres_network

networks:
  postgres_network:
    driver: bridge
